datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local

dashboards:
  default:
    kafka: https://grafana.com/api/dashboards/721


adminPassword: "S.l.m,4,12"


# datasources:
#   secretDefinition: 
#     apiVersion: 1
#     datasources:
#       - name: Prometheus
#         type: prometheus
#         access: proxy
#         orgId: 1
#         url: http://prometheus.monitoring.svc.cluster.local
#         version: 1
#         editable: true
#         isDefault: true
#       - name: Alertmanager
#         uid: alertmanager
#         type: alertmanager
#         access: proxy
#         orgId: 1
#         url: http://prometheus-alertmanager.monitoring.svc.cluster.local:9093
#         version: 1
#         editable: true