datasources:
  secretDefinition:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-server.default.svc.cluster.local:80
        version: 1
        editable: true
        isDefault: true
      - name: Alertmanager
        uid: alertmanager
        type: alertmanager
        access: proxy
        orgId: 1
        url: http://prometheus-alertmanager.default.svc.cluster.local:9093
        version: 1
        editable: true

dashboards:
  default:
    kafka:
      gnetId: 721
      revision: 1
      datasource: Prometheus
