extraScrapeConfigs: |
  - job_name: "kafka-jmx-exporter"
    honor_labels: true
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
        action: keep
        regex: default;kafka
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: jmx
