# extraScrapeConfigs:
# - job_name: 'kafka-jmx'
#   metrics_path: /metrics
#   scrape_interval: 15s
#   static_configs:
#     - targets: ['kafka.default.svc.cluster.local:5556']








# prometheus-values.yaml
server:
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: "kafka-jmx-exporter" # This is the distinct job for Kafka JMX Exporter metrics
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
          action: keep
          regex: default;kafka # Matches Kafka pods in the 'default' namespace
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: jmx # Matches only the JMX Exporter sidecar port (port 5566)
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: instance
      metrics_path: /metrics
      scheme: http
      honor_labels: true





# server:
#   extraScrapeConfigs:
#     - job_name: wordpress
#       kubernetes_sd_configs:
#         - role: endpoints
#           namespaces:
#             names:
#             - default
#       metrics_path: /metrics
#       relabel_configs:
#         - source_labels:
#             - job
#           target_label: __tmp_wordpress_job_name
#         - action: keep
#           source_labels:
#             - __meta_kubernetes_service_label_app_kubernetes_io_instance
#             - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
#           regex: (wordpress);true
#         - action: keep
#           source_labels:
#             - __meta_kubernetes_service_label_app_kubernetes_io_name
#             - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
#           regex: (wordpress);true
#         - action: keep
#           source_labels:
#             - __meta_kubernetes_endpoint_port_name
#           regex: metrics
#         - source_labels:
#             - __meta_kubernetes_endpoint_address_target_kind
#             - __meta_kubernetes_endpoint_address_target_name
#           separator: ;
#           regex: Node;(.*)
#           replacement: ${1}
#           target_label: node
#         - source_labels:
#             - __meta_kubernetes_endpoint_address_target_kind
#             - __meta_kubernetes_endpoint_address_target_name
#           separator: ;
#           regex: Pod;(.*)
#           replacement: ${1}
#           target_label: pod
#         - source_labels:
#             - __meta_kubernetes_namespace
#           target_label: namespace
#         - source_labels:
#             - __meta_kubernetes_service_name
#           target_label: service
#         - source_labels:
#             - __meta_kubernetes_pod_name
#           target_label: pod
#         - source_labels:
#             - __meta_kubernetes_pod_container_name
#           target_label: container
#         - action: drop
#           source_labels:
#             - __meta_kubernetes_pod_phase
#           regex: (Failed|Succeeded)
#         - source_labels:
#             - __meta_kubernetes_service_name
#           target_label: job
#           replacement: ${1}
#         - target_label: endpoint
#           replacement: metrics
#         - source_labels:
#             - __address__
#           target_label: __tmp_hash
#           modulus: 1
#           action: hashmod
#         - source_labels:
#             - __tmp_hash
#           regex: 0
#           action: keep
