apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx-metrics
  namespace: default  # or your Kafka namespace
spec:
  ports:
  - name: metrics
    port: 5556
    targetPort: 5556
  selector:
    app.kubernetes.io/name: kafka
