apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  labels:
    app: kafka
spec:
  # Reference Docker Hub secret to pull the image
  imagePullSecrets:
  - name: my-dockerhub-secret
 
  containers:
  - name: producer-image
    image: thissaleh/producer-image:4  # Use the latest image version
    imagePullPolicy: Always  # Ensures the latest image is always pulled

    # Resource limits for CPU and memory
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"

    # Health Checks
    livenessProbe:
      exec:
        command:
          - python
          - /app/health_check.py  # Adjust to the correct path if different
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 20
      failureThreshold: 6

    readinessProbe:
      exec:
        command:
          - python
          - /app/health_check.py  # Adjust to the correct path if different
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 20
      failureThreshold: 6

    # Mount volume for Kafka configuration
    volumeMounts:
    - name: kafka-config
      mountPath: /etc/kafka

  # Define an emptyDir volume for Kafka config
  volumes:
  - name: kafka-config
    emptyDir: {}
