apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer-slim
  labels:
    app: python
spec:
  containers:
  - name: python
    image: python:3.8-slim
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
    - name: kafka-config
      mountPath: /etc/kafka
  volumes:
  - name: kafka-config
    emptyDir: {}
