name: Build Kafka Consumer Docker Image

on:
  push:
    paths:
      - 'consumer/Dockerfile'
      - 'consumer/consumer.py'
      - 'consumer/health_check.py'
      - 'consumer/requirements.txt'
  pull_request:
    paths:
      - 'consumer/Dockerfile'
      - 'consumer/consumer.py'
      - 'consumer/health_check.py'
      - 'consumer/requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: thissaleh/consumer-image   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1   

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0   
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Python packages
        uses: actions/cache@v4.1.2   
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('consumer/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0  
        with:
          context: ./consumer
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=inline
