name: Build Kafka Consumer Docker Image

on:
  push:
    paths:
      - 'consumer/Dockerfile'
      - 'consumer/consumer.py'
      - 'consumer/health_check.py'
      - 'consumer/requirements.txt'

  pull_request:
    paths:
      - 'consumer/Dockerfile'
      - 'consumer/consumer.py'
      - 'consumer/health_check.py'
      - 'consumer/requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: thissaleh/consumer-image  # Replace with your Docker Hub repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3   

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Python packages
        uses: actions/cache@v4   
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('consumer/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4   
        with:
          context: ./consumer  # Path to Kafka consumer Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=inline
